#!/usr/bin/env python3
"""Generate MediCore's simulated source-system file deliveries.

Writes one load's files into the landing layout described in
phase3_architecture.md section 3:

    <out-dir>/<entity>/load_<n>/<file>

Records are generated deterministically on the driver, so a load can be
regenerated byte-for-byte from its seed. Writing goes through one of two
backends:

  spark  Any Spark environment, including Databricks writing straight into a
         Unity Catalog Volume (--out-dir /Volumes/<catalog>/landing/source_files).
  local  Plain filesystem via pyarrow, for running without a cluster.

`--writer auto` (the default) picks Spark when a session is available.

Usage:
    python3 tools/generate_source_data.py --load 1
    python3 tools/generate_source_data.py --load 1 \
        --out-dir /Volumes/medicore_dev/landing/source_files
"""

import argparse
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from data_generator import entities, schemas  # noqa: E402


def build_load_1(rng: random.Random, patients: int, providers: int, encounters: int) -> dict:
    """Load 1 is the clean baseline: full referential integrity, valid
    categoricals, no duplicates (README.md section 5)."""
    facility_rows = entities.generate_facilities()
    provider_rows = entities.generate_providers(rng, providers)
    patient_rows = entities.generate_patients(rng, patients)
    encounter_rows = entities.generate_encounters(rng, encounters, patient_rows, provider_rows)
    lab_rows = entities.generate_lab_results(rng, encounter_rows)
    prescription_rows = entities.generate_prescriptions(rng, encounter_rows)
    claim_rows = entities.generate_claims(
        rng, encounter_rows, patient_rows, lab_rows, prescription_rows
    )
    return {
        "facilities": facility_rows,
        "providers": provider_rows,
        "patients": patient_rows,
        "encounters": encounter_rows,
        "lab_results": lab_rows,
        "prescriptions": prescription_rows,
        "claims": claim_rows,
    }


def build_load(load: int, rng: random.Random, patients: int, providers: int, encounters: int) -> dict:
    if load == 1:
        return build_load_1(rng, patients, providers, encounters)
    raise NotImplementedError(f"load {load} is not implemented yet; only load 1 exists so far")


def _spark_session(create: bool):
    try:
        from pyspark.sql import SparkSession
    except ImportError:
        return None
    active = SparkSession.getActiveSession()
    if active is not None or not create:
        return active
    return SparkSession.builder.appName("medicore-source-data").getOrCreate()


def resolve_writer(preference: str):
    """Return (name, write_fn) where write_fn takes (entity, rows, target).

    `auto` uses Spark only when a session is already active, which is the
    case inside a Databricks notebook or job but not on a plain laptop, where
    spinning up a JVM to write a few MB would just be overhead.
    """
    if preference != "local":
        session = _spark_session(create=preference == "spark")
        if session is not None:
            from data_generator import spark_writers

            return "spark", lambda entity, rows, target: spark_writers.write_entity(
                session, entity, rows, target
            )
        if preference == "spark":
            raise SystemExit("--writer spark requested but pyspark is not available")

    from data_generator import writers

    return "local", writers.write_entity


def write_load(data: dict, out_dir: str, load: int, write_fn) -> list[tuple[str, int, str]]:
    written = []
    for entity, rows in data.items():
        target = f"{out_dir.rstrip('/')}/{entity}/load_{load}/{schemas.ENTITIES[entity]['filename']}"
        write_fn(entity, rows, target)
        written.append((entity, len(rows), target))
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--load", type=int, default=1, help="Load number to generate (1-5)")
    parser.add_argument(
        "--out-dir",
        default="generated_data",
        help="Landing root. On Databricks: /Volumes/<catalog>/landing/source_files",
    )
    parser.add_argument("--writer", choices=["auto", "local", "spark"], default="auto")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--patients", type=int, default=2000)
    parser.add_argument("--providers", type=int, default=120)
    parser.add_argument("--encounters", type=int, default=10000)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    data = build_load(args.load, rng, args.patients, args.providers, args.encounters)

    backend, write_fn = resolve_writer(args.writer)
    written = write_load(data, args.out_dir, args.load, write_fn)

    print(f"Load {args.load} written via {backend} writer to {args.out_dir} (seed {args.seed})")
    for entity, count, target in written:
        print(f"  {entity:<15} {count:>7,} rows  {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
